// Canonical notification event keys (spec §34/§60). Single source of truth
// so the seed data, the dispatch service, and the admin template/rule UI
// can never drift on what an event is actually called.

export const NOTIFICATION_EVENTS = {
  DOCUMENT_APPROVAL_PENDING: "DOCUMENT_APPROVAL_PENDING",
  DOCUMENT_APPROVED: "DOCUMENT_APPROVED",
  DOCUMENT_REJECTED: "DOCUMENT_REJECTED",
  FILE_ISSUE_REQUESTED: "FILE_ISSUE_REQUESTED",
  FILE_ISSUED: "FILE_ISSUED",
  FILE_DUE_TOMORROW: "FILE_DUE_TOMORROW",
  FILE_OVERDUE: "FILE_OVERDUE",
  FILE_EXTENSION_REQUESTED: "FILE_EXTENSION_REQUESTED",
  FILE_EXTENSION_APPROVED: "FILE_EXTENSION_APPROVED",
  FILE_EXTENSION_REJECTED: "FILE_EXTENSION_REJECTED",
  TYPE_TEST_CERTIFICATE_EXPIRING: "TYPE_TEST_CERTIFICATE_EXPIRING",
} as const;

export type NotificationEventKey = (typeof NOTIFICATION_EVENTS)[keyof typeof NOTIFICATION_EVENTS];

export const NOTIFICATION_EVENT_KEYS = Object.values(NOTIFICATION_EVENTS);
