// Canonical status vocabularies (spec §21, §30, §37, §73). Stored as plain
// strings in the DB (not DB enums) so admins can extend workflows without a
// migration, but the *default* set the app ships with and reasons about is
// fixed here.

export const DOCUMENT_VERSION_STATUS = {
  DRAFT: "DRAFT",
  UPLOADED: "UPLOADED",
  UNDER_REVIEW: "UNDER_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  SUPERSEDED: "SUPERSEDED",
  ARCHIVED: "ARCHIVED",
  EXPIRED: "EXPIRED",
} as const;

export const STORAGE_STATUS = {
  NFS_STORED: "NFS_STORED",
  LOCAL_PENDING_SYNC: "LOCAL_PENDING_SYNC",
  SYNCING: "SYNCING",
  SYNC_FAILED: "SYNC_FAILED",
  SYNCED: "SYNCED",
} as const;

export const PROJECT_STAGE_STATUS = {
  INCOMPLETE: "INCOMPLETE",
  UNDER_REVIEW: "UNDER_REVIEW",
  COMPLETED: "COMPLETED",
} as const;

export const PROJECT_STATUS = {
  DRAFT: "DRAFT",
  ORDER_RECEIVED: "ORDER_RECEIVED",
  ENGINEERING: "ENGINEERING",
  PROCUREMENT: "PROCUREMENT",
  MANUFACTURING: "MANUFACTURING",
  TESTING: "TESTING",
  QA_REVIEW: "QA_REVIEW",
  READY_FOR_DISPATCH: "READY_FOR_DISPATCH",
  DISPATCHED: "DISPATCHED",
  PROJECT_CLOSURE: "PROJECT_CLOSURE",
  COMPLETED: "COMPLETED",
  ON_HOLD: "ON_HOLD",
  CANCELLED: "CANCELLED",
} as const;

export const FILE_ISSUE_STATUS = {
  REQUESTED: "REQUESTED",
  APPROVED: "APPROVED",
  ISSUED: "ISSUED",
  RETURNED: "RETURNED",
  OVERDUE: "OVERDUE",
  EXTENSION_REQUESTED: "EXTENSION_REQUESTED",
  EXTENSION_APPROVED: "EXTENSION_APPROVED",
  EXTENSION_REJECTED: "EXTENSION_REJECTED",
  LOST: "LOST",
  CANCELLED: "CANCELLED",
} as const;

export const APPROVAL_DECISION = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CHANGES_REQUESTED: "CHANGES_REQUESTED",
} as const;
