// Renders an EJS template to a PDF buffer via a headless Chromium instance
// (Puppeteer). Kept independent of utils/whatsapp.js's own Chromium usage -
// document generation is core/mandatory, WhatsApp stays optional/best-effort.
const ejs = require('ejs');
const path = require('path');
const puppeteer = require('puppeteer');

let browserPromise = null;

function escapeHtml(str) {
  return String(str).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

// A single shared browser instance is reused across requests (launching
// Chromium per-request would be slow); Puppeteer opens one page per PDF.
function getBrowser() {
  if (!browserPromise) {
    browserPromise = puppeteer.launch({
      headless: true,
      executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    }).catch(err => {
      browserPromise = null; // allow retry on next call instead of caching a rejected launch
      throw err;
    });
  }
  return browserPromise;
}

async function renderPdf(templateName, data) {
  const templatePath = path.join(__dirname, '..', 'views', 'documents', 'generate', templateName);
  const html = await ejs.renderFile(templatePath, data);

  const browser = await getBrowser();
  const page = await browser.newPage();
  try {
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '18mm', bottom: '16mm', left: '14mm', right: '14mm' },
      displayHeaderFooter: true,
      headerTemplate: '<div></div>',
      footerTemplate: `
        <div style="width:100%;font-size:8px;color:#888;padding:0 14mm;display:flex;justify-content:space-between;font-family:Arial,sans-serif;">
          <span>Generated by ${escapeHtml(data.companyName || 'TRAFO 360')}</span>
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>`
    });
    return pdfBuffer;
  } finally {
    await page.close();
  }
}

// Closes the shared browser - used on graceful shutdown / by tests.
async function closeBrowser() {
  if (browserPromise) {
    const browser = await browserPromise.catch(() => null);
    if (browser) await browser.close();
    browserPromise = null;
  }
}

module.exports = { renderPdf, closeBrowser };
